#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/kchmck/vim-coffee-script",
  "git://github.com/mileszs/ack.vim",
  "git://github.com/digitaltoad/vim-jade",
  [ "git://github.com/wincent/Command-T.git", 'rake make']
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["nerdtree-ack", "17196",  "plugin"]
]

#  ["LustyJuggler", "17547", "plugin"]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url,post_init|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
  `cd #{dir} && #{post_init}` if post_init
end

vim_org_scripts.each do |name, script_id, script_type, post_init|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  `cd #{File.dirname(local_file)} && #{post_init}` if post_init
end
